dist: trusty
language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules
    - '.eslintcache'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

install: true
sudo: false
script:
- npm test